/**
 * Base mundial de aeroportos para autocomplete — sem custo de API.
 * iata · cidade · país. Adicione novos aeroportos livremente no mesmo formato.
 */
module.exports = [
  // ---------- CIDADES COM MÚLTIPLOS AEROPORTOS (busca todos de uma vez) ----------
  { iata: "SAO", city: "São Paulo (todos os aeroportos)", country: "Brasil" },
  { iata: "RIO", city: "Rio de Janeiro (todos os aeroportos)", country: "Brasil" },
  { iata: "BUE", city: "Buenos Aires (todos os aeroportos)", country: "Argentina" },
  { iata: "NYC", city: "Nova York (todos os aeroportos)", country: "Estados Unidos" },
  { iata: "LON", city: "Londres (todos os aeroportos)", country: "Reino Unido" },
  { iata: "PAR", city: "Paris (todos os aeroportos)", country: "França" },
  { iata: "TYO", city: "Tóquio (todos os aeroportos)", country: "Japão" },
  { iata: "MIL", city: "Milão (todos os aeroportos)", country: "Itália" },

  // ---------- BRASIL ----------
  { iata: "MAO", city: "Manaus", country: "Brasil" },
  { iata: "GRU", city: "São Paulo (Guarulhos)", country: "Brasil" },
  { iata: "CGH", city: "São Paulo (Congonhas)", country: "Brasil" },
  { iata: "VCP", city: "Campinas (Viracopos)", country: "Brasil" },
  { iata: "GIG", city: "Rio de Janeiro (Galeão)", country: "Brasil" },
  { iata: "SDU", city: "Rio de Janeiro (Santos Dumont)", country: "Brasil" },
  { iata: "BSB", city: "Brasília", country: "Brasil" },
  { iata: "FOR", city: "Fortaleza", country: "Brasil" },
  { iata: "REC", city: "Recife", country: "Brasil" },
  { iata: "SSA", city: "Salvador", country: "Brasil" },
  { iata: "BEL", city: "Belém", country: "Brasil" },
  { iata: "CNF", city: "Belo Horizonte (Confins)", country: "Brasil" },
  { iata: "POA", city: "Porto Alegre", country: "Brasil" },
  { iata: "CWB", city: "Curitiba", country: "Brasil" },
  { iata: "FLN", city: "Florianópolis", country: "Brasil" },
  { iata: "NAT", city: "Natal", country: "Brasil" },
  { iata: "JPA", city: "João Pessoa", country: "Brasil" },
  { iata: "MCZ", city: "Maceió", country: "Brasil" },
  { iata: "AJU", city: "Aracaju", country: "Brasil" },
  { iata: "SLZ", city: "São Luís", country: "Brasil" },
  { iata: "THE", city: "Teresina", country: "Brasil" },
  { iata: "PMW", city: "Palmas", country: "Brasil" },
  { iata: "CGB", city: "Cuiabá", country: "Brasil" },
  { iata: "CGR", city: "Campo Grande", country: "Brasil" },
  { iata: "GYN", city: "Goiânia", country: "Brasil" },
  { iata: "VIX", city: "Vitória", country: "Brasil" },
  { iata: "PVH", city: "Porto Velho", country: "Brasil" },
  { iata: "RBR", city: "Rio Branco", country: "Brasil" },
  { iata: "BVB", city: "Boa Vista", country: "Brasil" },
  { iata: "MCP", city: "Macapá", country: "Brasil" },
  { iata: "STM", city: "Santarém", country: "Brasil" },
  { iata: "IGU", city: "Foz do Iguaçu", country: "Brasil" },
  { iata: "NVT", city: "Navegantes", country: "Brasil" },
  { iata: "BPS", city: "Porto Seguro", country: "Brasil" },
  { iata: "IOS", city: "Ilhéus", country: "Brasil" },
  { iata: "JDO", city: "Juazeiro do Norte", country: "Brasil" },
  { iata: "IMP", city: "Imperatriz", country: "Brasil" },
  { iata: "MAB", city: "Marabá", country: "Brasil" },
  { iata: "FEN", city: "Fernando de Noronha", country: "Brasil" },
  { iata: "JJD", city: "Jericoacoara", country: "Brasil" },
  { iata: "LDB", city: "Londrina", country: "Brasil" },
  { iata: "MGF", city: "Maringá", country: "Brasil" },
  { iata: "UDI", city: "Uberlândia", country: "Brasil" },
  { iata: "RAO", city: "Ribeirão Preto", country: "Brasil" },
  { iata: "SJP", city: "São José do Rio Preto", country: "Brasil" },
  { iata: "CXJ", city: "Caxias do Sul", country: "Brasil" },

  // ---------- AMÉRICA DO SUL ----------
  { iata: "EZE", city: "Buenos Aires (Ezeiza)", country: "Argentina" },
  { iata: "AEP", city: "Buenos Aires (Aeroparque)", country: "Argentina" },
  { iata: "COR", city: "Córdoba", country: "Argentina" },
  { iata: "MDZ", city: "Mendoza", country: "Argentina" },
  { iata: "BRC", city: "Bariloche", country: "Argentina" },
  { iata: "SCL", city: "Santiago", country: "Chile" },
  { iata: "LIM", city: "Lima", country: "Peru" },
  { iata: "CUZ", city: "Cusco", country: "Peru" },
  { iata: "BOG", city: "Bogotá", country: "Colômbia" },
  { iata: "MDE", city: "Medellín", country: "Colômbia" },
  { iata: "CTG", city: "Cartagena", country: "Colômbia" },
  { iata: "UIO", city: "Quito", country: "Equador" },
  { iata: "GYE", city: "Guayaquil", country: "Equador" },
  { iata: "GPS", city: "Galápagos", country: "Equador" },
  { iata: "CCS", city: "Caracas", country: "Venezuela" },
  { iata: "MVD", city: "Montevidéu", country: "Uruguai" },
  { iata: "PDP", city: "Punta del Este", country: "Uruguai" },
  { iata: "ASU", city: "Assunção", country: "Paraguai" },
  { iata: "VVI", city: "Santa Cruz de la Sierra", country: "Bolívia" },
  { iata: "LPB", city: "La Paz", country: "Bolívia" },
  { iata: "GEO", city: "Georgetown", country: "Guiana" },
  { iata: "PBM", city: "Paramaribo", country: "Suriname" },
  { iata: "CAY", city: "Caiena", country: "Guiana Francesa" },

  // ---------- AMÉRICA DO NORTE / CENTRAL / CARIBE ----------
  { iata: "MIA", city: "Miami", country: "Estados Unidos" },
  { iata: "MCO", city: "Orlando", country: "Estados Unidos" },
  { iata: "FLL", city: "Fort Lauderdale", country: "Estados Unidos" },
  { iata: "JFK", city: "Nova York (JFK)", country: "Estados Unidos" },
  { iata: "EWR", city: "Nova York (Newark)", country: "Estados Unidos" },
  { iata: "BOS", city: "Boston", country: "Estados Unidos" },
  { iata: "IAD", city: "Washington", country: "Estados Unidos" },
  { iata: "ATL", city: "Atlanta", country: "Estados Unidos" },
  { iata: "ORD", city: "Chicago", country: "Estados Unidos" },
  { iata: "DFW", city: "Dallas", country: "Estados Unidos" },
  { iata: "IAH", city: "Houston", country: "Estados Unidos" },
  { iata: "DEN", city: "Denver", country: "Estados Unidos" },
  { iata: "LAS", city: "Las Vegas", country: "Estados Unidos" },
  { iata: "LAX", city: "Los Angeles", country: "Estados Unidos" },
  { iata: "SFO", city: "São Francisco", country: "Estados Unidos" },
  { iata: "SEA", city: "Seattle", country: "Estados Unidos" },
  { iata: "YYZ", city: "Toronto", country: "Canadá" },
  { iata: "YUL", city: "Montreal", country: "Canadá" },
  { iata: "YVR", city: "Vancouver", country: "Canadá" },
  { iata: "MEX", city: "Cidade do México", country: "México" },
  { iata: "CUN", city: "Cancún", country: "México" },
  { iata: "GDL", city: "Guadalajara", country: "México" },
  { iata: "PTY", city: "Cidade do Panamá", country: "Panamá" },
  { iata: "SJO", city: "San José", country: "Costa Rica" },
  { iata: "GUA", city: "Guatemala", country: "Guatemala" },
  { iata: "SAL", city: "San Salvador", country: "El Salvador" },
  { iata: "HAV", city: "Havana", country: "Cuba" },
  { iata: "PUJ", city: "Punta Cana", country: "República Dominicana" },
  { iata: "SDQ", city: "Santo Domingo", country: "República Dominicana" },
  { iata: "AUA", city: "Aruba", country: "Aruba" },
  { iata: "CUR", city: "Curaçao", country: "Curaçao" },
  { iata: "NAS", city: "Nassau", country: "Bahamas" },
  { iata: "SJU", city: "San Juan", country: "Porto Rico" },
  { iata: "KIN", city: "Kingston", country: "Jamaica" },

  // ---------- EUROPA ----------
  { iata: "LIS", city: "Lisboa", country: "Portugal" },
  { iata: "OPO", city: "Porto", country: "Portugal" },
  { iata: "FNC", city: "Funchal (Madeira)", country: "Portugal" },
  { iata: "MAD", city: "Madri", country: "Espanha" },
  { iata: "BCN", city: "Barcelona", country: "Espanha" },
  { iata: "AGP", city: "Málaga", country: "Espanha" },
  { iata: "PMI", city: "Palma de Maiorca", country: "Espanha" },
  { iata: "CDG", city: "Paris (Charles de Gaulle)", country: "França" },
  { iata: "ORY", city: "Paris (Orly)", country: "França" },
  { iata: "NCE", city: "Nice", country: "França" },
  { iata: "LHR", city: "Londres (Heathrow)", country: "Reino Unido" },
  { iata: "LGW", city: "Londres (Gatwick)", country: "Reino Unido" },
  { iata: "MAN", city: "Manchester", country: "Reino Unido" },
  { iata: "EDI", city: "Edimburgo", country: "Reino Unido" },
  { iata: "DUB", city: "Dublin", country: "Irlanda" },
  { iata: "AMS", city: "Amsterdã", country: "Holanda" },
  { iata: "BRU", city: "Bruxelas", country: "Bélgica" },
  { iata: "FRA", city: "Frankfurt", country: "Alemanha" },
  { iata: "MUC", city: "Munique", country: "Alemanha" },
  { iata: "BER", city: "Berlim", country: "Alemanha" },
  { iata: "ZRH", city: "Zurique", country: "Suíça" },
  { iata: "GVA", city: "Genebra", country: "Suíça" },
  { iata: "VIE", city: "Viena", country: "Áustria" },
  { iata: "CPH", city: "Copenhague", country: "Dinamarca" },
  { iata: "ARN", city: "Estocolmo", country: "Suécia" },
  { iata: "OSL", city: "Oslo", country: "Noruega" },
  { iata: "HEL", city: "Helsinque", country: "Finlândia" },
  { iata: "KEF", city: "Reykjavík", country: "Islândia" },
  { iata: "FCO", city: "Roma (Fiumicino)", country: "Itália" },
  { iata: "MXP", city: "Milão (Malpensa)", country: "Itália" },
  { iata: "VCE", city: "Veneza", country: "Itália" },
  { iata: "NAP", city: "Nápoles", country: "Itália" },
  { iata: "ATH", city: "Atenas", country: "Grécia" },
  { iata: "JTR", city: "Santorini", country: "Grécia" },
  { iata: "IST", city: "Istambul", country: "Turquia" },
  { iata: "PRG", city: "Praga", country: "Tchéquia" },
  { iata: "BUD", city: "Budapeste", country: "Hungria" },
  { iata: "WAW", city: "Varsóvia", country: "Polônia" },
  { iata: "KRK", city: "Cracóvia", country: "Polônia" },
  { iata: "OTP", city: "Bucareste", country: "Romênia" },
  { iata: "ZAG", city: "Zagreb", country: "Croácia" },
  { iata: "SPU", city: "Split", country: "Croácia" },

  // ---------- ORIENTE MÉDIO / ÁFRICA ----------
  { iata: "DXB", city: "Dubai", country: "Emirados Árabes" },
  { iata: "AUH", city: "Abu Dhabi", country: "Emirados Árabes" },
  { iata: "DOH", city: "Doha", country: "Catar" },
  { iata: "JED", city: "Jeddah", country: "Arábia Saudita" },
  { iata: "RUH", city: "Riade", country: "Arábia Saudita" },
  { iata: "TLV", city: "Tel Aviv", country: "Israel" },
  { iata: "AMM", city: "Amã", country: "Jordânia" },
  { iata: "CAI", city: "Cairo", country: "Egito" },
  { iata: "CMN", city: "Casablanca", country: "Marrocos" },
  { iata: "RAK", city: "Marrakech", country: "Marrocos" },
  { iata: "JNB", city: "Joanesburgo", country: "África do Sul" },
  { iata: "CPT", city: "Cidade do Cabo", country: "África do Sul" },
  { iata: "NBO", city: "Nairóbi", country: "Quênia" },
  { iata: "ADD", city: "Adis Abeba", country: "Etiópia" },
  { iata: "LOS", city: "Lagos", country: "Nigéria" },
  { iata: "SID", city: "Sal", country: "Cabo Verde" },
  { iata: "RAI", city: "Praia", country: "Cabo Verde" },
  { iata: "LAD", city: "Luanda", country: "Angola" },
  { iata: "MPM", city: "Maputo", country: "Moçambique" },
  { iata: "MRU", city: "Ilhas Maurício", country: "Maurício" },
  { iata: "SEZ", city: "Seychelles", country: "Seychelles" },

  // ---------- ÁSIA ----------
  { iata: "NRT", city: "Tóquio (Narita)", country: "Japão" },
  { iata: "HND", city: "Tóquio (Haneda)", country: "Japão" },
  { iata: "KIX", city: "Osaka", country: "Japão" },
  { iata: "ICN", city: "Seul", country: "Coreia do Sul" },
  { iata: "PEK", city: "Pequim", country: "China" },
  { iata: "PVG", city: "Xangai", country: "China" },
  { iata: "CAN", city: "Cantão (Guangzhou)", country: "China" },
  { iata: "HKG", city: "Hong Kong", country: "Hong Kong" },
  { iata: "TPE", city: "Taipei", country: "Taiwan" },
  { iata: "BKK", city: "Bangkok", country: "Tailândia" },
  { iata: "HKT", city: "Phuket", country: "Tailândia" },
  { iata: "CNX", city: "Chiang Mai", country: "Tailândia" },
  { iata: "SIN", city: "Singapura", country: "Singapura" },
  { iata: "KUL", city: "Kuala Lumpur", country: "Malásia" },
  { iata: "CGK", city: "Jacarta", country: "Indonésia" },
  { iata: "DPS", city: "Bali (Denpasar)", country: "Indonésia" },
  { iata: "MNL", city: "Manila", country: "Filipinas" },
  { iata: "SGN", city: "Ho Chi Minh", country: "Vietnã" },
  { iata: "HAN", city: "Hanói", country: "Vietnã" },
  { iata: "DEL", city: "Nova Délhi", country: "Índia" },
  { iata: "BOM", city: "Mumbai", country: "Índia" },
  { iata: "CMB", city: "Colombo", country: "Sri Lanka" },
  { iata: "KTM", city: "Katmandu", country: "Nepal" },
  { iata: "MLE", city: "Maldivas (Malé)", country: "Maldivas" },

  // ---------- OCEANIA ----------
  { iata: "SYD", city: "Sydney", country: "Austrália" },
  { iata: "MEL", city: "Melbourne", country: "Austrália" },
  { iata: "BNE", city: "Brisbane", country: "Austrália" },
  { iata: "AKL", city: "Auckland", country: "Nova Zelândia" },
  { iata: "NAN", city: "Nadi (Fiji)", country: "Fiji" },
  { iata: "PPT", city: "Papeete (Taiti)", country: "Polinésia Francesa" }
];
